export const Tables = {
	CONTRACTVERSION: "ContractVersion",
	SQLSCRIPTMIGRATIONS: "SqlScriptMigrations",
	HOTELS: "Hotels",
	HOTELIMAGES: "HotelImages",
	ROOMTYPEIMAGES: "RoomTypeImages",
	ROOMTYPES: "RoomTypes",
	ROOMS: "Rooms",
	PRICES: "Prices",
	FACILITIES: "Facilities",
	ROOMFACILITIES: "RoomFacilities",
	RESERVATIONS: "Reservations",
	RESERVATIONROOMTYPES: "ReservationRoomTypes",
	OWNERBANKACCOUNTDETAILS: "OwnerBankAccountDetails",
};
